### ISSUE TITLE
Eclipse test instance lacks tsplugin

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/cobigen#1033]
### Expected behavior

As a CobiGen developer, I want SWT bot tests in `eclipse-test` plugin to work correctly so that I can find any real issue if my code is broken.

### Actual behavior
When running the `eclipse-test` SWT bot tests inside my Eclipse, every test is passing. However, when running `eclipse-test` SWT bot tests from a Maven console, the following test fails:

```bash
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 198.544 sec <<< FAILURE! - in com.devonfw.cobigen.eclipse.test.OpenAPITest
2019-10-18 11:27:00,503 [INFO ]  testServiceBasedOpenAPIGeneration(com.devonfw.cobigen.eclipse.test.OpenAPITest)  Time elapsed: 108.609 sec  <<< ERROR!
2019-10-18 11:27:00,504 [INFO ]  org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 40000 ms.: The shell 'Success' did not activate
```

It fails because the `tsmerge` is not found. Therefore the 'Success' shell doesn't get activated. 

Investigating the problem, I have found out that the eclipse instance that gets run on **Maven** doesn't have the `tsplugin` installed. While the one running inside my **Eclipse** does install the `tsplugin`.

I don't know why it is not installed on the Maven Eclipse. It is not a local issue as in Jenkins we can see the same behavior.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Go to `cobigen-eclipse` parent folder.
2. Open console and run `mvn clean -Dtest=OpenAPITest -U -Pp2-build-mars,p2-build-stable`

### Comments/Hints:

Any hint that you can give us @maybeec ?

### Affected version:

* OS: Windows/Linux

**Comment by maybeec** [comment]
Currently try to get the tests running with jdk 11, then I will have a look at this, but it seems strange for me

**Comment by MikeSchumacherCapgemini** [comment]
There are no issues with the currently released plugin versions
