### ISSUE TITLE
Failing tests due to JDK 11 version

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/cobigen#1083]
### Description

Due to the migration from JDK 8 to JDK 11 there are some plug-ins which tests are failing. We should check these issues for next release.

### Affected plug-ins:
1. Property plug-in.
2. Text merger.
3. Java plug-in.
4. XML plug-in
5. OpenAPI plug-in

**Comment by maybeec** [comment]
@jdiazgon, I fixed quite a long and implemented travis builds and deployment.
The tests are now running on openjdk8 + openjdk11 all the time. Unfortunately, I see a lot of tests failing especially with openjdk8. So we need to get this fixed as well. Please find the builds here: 
https://travis-ci.com/github/devonfw/cobigen/branches

**Comment by jdiazgon** [comment]
Thanks @maybeec for your great support. Our colleague @sujithmn is working on them.
