### ISSUE TITLE
cobigen-cli does not seem to properly resolve classes from dependencies

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1113]
I get this error from `cobigen-cli`:
```
[ERROR] Compiled class net/sf/mmm/util/entity/api/MutableRevisionedEntity has not been found. Most probably you need to build project
```

I have replaced `devon4j` default templates with custom templates. The requested class comes from a JAR dependency (`mmm-util-entity`) and that dependency is a transitive dependency of the custom templates project. I have checked my `software/cobigen-cli/classPath.txt` and it contains `/Users/hohwille/.m2/repository/net/sf/m-m-m/mmm-util-entity/8.6.0/mmm-util-entity-8.6.0.jar` and that file exists on my disc and has the proper content including the requested class.

I have no idea how `cobigen-cli` builds up his classpath.
* does it include all dependencies from the templates project?
* I assume it will have to add all dependencies for cobigen itself.
* does it also include the dependencies of the current maven project where the generation is invoked?
* if yes, the current project in `$PWD` or the module that is containing the code to taje as input for generation?
* does cobigen do any classpath shading to avoid conflicts in dependencies of cobigen itself and the projects/templates dependencies (if different versions of a library are used in cobigen itself and the custom templates project for a specific project)?

Any ideas why the above class is not found or what I could do about it?

**Comment by hohwille** [comment]
https://github.com/devonfw/cobigen/blob/bb492e477cd46dbb8f6eaf71004047418380ecf1/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/utils/ParsingUtils.java#L63

This is rather poor exception handling. Following `devon4j` coding conventions you should never loose stacktraces. When catching exceptions either rethrow including the catched exception as cause to the new exception or log the exception by supplying it to `slf4j` as such.

**Comment by hohwille** [comment]
Looking at `ParsingUtils` I can answer most of the above questions about classpath/classloading myself.
It seems I found another bug in `mmm-code` here: the collecting of all the transitive dependencies is incorrect.

**Comment by maybeec** [comment]
@hohwille, do you mean, as there is more to do in mmm-code or do we have to integrate a new version, which you already adapted?

**Comment by hohwille** [comment]
With PR #1114 merged and release out, we can IMHO close this. If I find remaining or new problems I better file a new bug.
