### ISSUE TITLE
tsplugin nestserver update not working

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1158]
### Expected behavior

As a user, I want to update tsplugin so that I can use the new features, bugfixes.

### Actual behavior

Updating the tsplugin seems to work, but my bugs of the ts-merger are not resolved.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install version x of the ts-plugin in your eclipse
2. run once a generation which will trigger the ts-merger (the nestserver will be downloaded)
3. install a new version x+1 of the ts-plugin, which includes changes in the ts-merger
4. re-run the generation and check whether the fixed behavior of the ts-plugin is resolved

### Comments/Hints:

The problem occurs as the nestserver is stored without any information of the version into the home folder. The logic of the ts-plugin simply checks the nestserver to exist and if so, will not do anything, but simply run it. In case a new ts-plugin version will declare a new version of the nestserver, this will never be taken up as the binary is never updated if existing.

In addition, please respect the requirement, that there should be the ability to maintain multiple versions of the nestserver as you might have multiple installations of the ts-plugin on your machine in different versions. Each of the plugin should get its corresponding nestserver version on start.

### Affected version:

* OS: Windows/Linux/Mac?
* Browser: Chrome/Firefox/Safari?

**Comment by jdiazgon** [comment]
Let me briefly explain the logic implemented:

1. tsplugin calls the core in order to connect to the external server. If the server is already running (because on a previous execution was already started), it sends the needed requests (to merge, to read the input file...)
2. If the server is not up and running, tries to find it. This will try to find the server with version defined on the current tsplugin. If it is not found, it downloads the server and removes older versions.

Most probably @maybeec it did not download the latest server version because the old server was already deployed.

**Comment by maybeec** [comment]
ok, but is the server stopped after generation? I could imagine, that after processing one generate request we should even close the nestserver, otherwise we would end up in a lot of zombie processes and would not allow to have multiple servers of different versions running in parallel.
Anyhow, how do you get the version of the currently installed nestserver?

**Comment by jdiazgon** [comment]
> ok, but is the server stopped after generation? 

Yes, we call method `terminateProcessConnection()` after a request as you can see [here](https://github.com/devonfw/cobigen/blob/master/cobigen/cobigen-tsplugin/src/main/java/com/devonfw/cobigen/tsplugin/inputreader/TypeScriptInputReader.java#L226). Though as far as I remember, there are some permission issues an the server does not get closed always. That is why we added a timeout to the server, that it gets closed after some minutes. 

I think the best approach would be creating a new REST service on the server that destroys himself when gets called. That would avoid permission issues. However, that may add performance issues if we need to stop and deploy the server each time we make new requests.

> how do you get the version of the currently installed nestserver?

The tsplugin pom defines the version of the nestserver that needs to be used. As you can find [here](https://github.com/devonfw/cobigen/blob/master/cobigen/cobigen-tsplugin/pom.xml#L18).

**Comment by maybeec** [comment]
ok, so I understood, that the only issue currently is, that we are replacing the nestserver on update, but we should be able to maintain multiple versions simultaneously.

**Comment by jdiazgon** [comment]
That's right

**Comment by MikeSchumacherCapgemini** [comment]
Should be resolved
