### ISSUE TITLE
Improve CLI deployment

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1159]
As a user of the devonfw ide, I want to be able to able to update cobigen cli so that I can work with the newest version of CobiGen after executing one single update command. (devonfw/ide#340)

As a user of cobigen, I want to be able to download cobigen as a cli, so that I can execute it in any environment of my choice.

**Comment by hohwille** [comment]
IMHO the entire javaagent can be omitted and entirely removed. You may also want to create a separate issue/story for doing so and keep the change to fix this issue minimal.
However, including a POM and using maven to resolve dependencies and calculate a `classPath.txt` file is IMHO a pointless hack.
Simply put all required dependencies in lib folder and let the bin launch script `cg` build the classpath using all JARs in that lib folder.
You may also easily address #1169 by letting the `cg` launch script check if a `templates` folder is present somewhere (should be outside `software/cobigen-cli`) and if so add all containing JARs to the classpath. Then add a smart mechanism to cobigen core to find templates and determine some overruling/priority mechanism allowing to replace the default templates.
