### ISSUE TITLE
Cobigen fails to generate without doing adapt templates

### ISSUE THREAD

**Issue by ravicm2** [devonfw/cobigen#1160]
### Expected behavior

Expected selected code to be generated

### Actual behavior
But thrown error saying templates not found when i clicked on cobigen-> generate. it downloaded the templates but still it failed with the error no templates.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create an entity class
2. right click on the class, click cobigen-> generate

### Comments/Hints:

Input:
public class EmployeeEntity {
  private String name;
  private Integer age;
  private String location;
}

Selected Resources:
1. CRUD Rest service
2. CRUD SpringData Repository
3. CRUD UC logic
4. Entity Infrastructure
5. TOs

### Affected version:
* devon-ide : 2020.04.001
* OS: Windows
* Browser: Chrome

**Comment by maybeec** [comment]
@ravicm2 could you give it another try? Should be fixed now

**Comment by ravicm2** [comment]
> @ravicm2 could you give it another try? Should be fixed now

yes sure @maybeec . I will try and let you know asap.

**Comment by ravicm2** [comment]
> > @ravicm2 could you give it another try? Should be fixed now
> 
> yes sure @maybeec . I will try and let you know asap.

Hi @maybeec , i checked . its working perfectly . shall i close the ticket?
