### ISSUE TITLE
CLI option for increment not working

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1170]
I tried cobigen-cli option `-i` to specify an increment:
```
  -i, --increments=<increments>[,<increments>...]
                       List of increments that will be generated. They need to be
                         specified with numbers separated by comma.
```
As nothing is further specified, I assume that the increment has to be specified by its `name` attribute from `templates.xml`.
I therefore supplied that value via Copy&Paste (to ensure no typo happens):
```
    <increment name="tos" description="Common (ETO)">
```
So I called:
```
cg generate -i tos -v app/src/main/java/com/customer/project/app/component/dataaccess/api/FooEntity.java
[DEBUG] Input files and output root path confirmed to be valid.
[INFO ] As you did not specify where the code will be generated, we will use the project of your current Input file.
[DEBUG] Generating to: /Users/hohwille/projects/myproject/workspaces/main/app/core
[INFO ] No increment with that name has been found, Please provide correct increment name and try again ! Thank you
```
If the last line means that generation failed because the specified increment `tos` could not be found, I would expect this to be an ERROR and not an INFO.

**Comment by hohwille** [comment]
BTW: If there is only one single increment available it is rather rediculous that CobiGen CLI is asking wheter to generate 
* all
* the only available increment.

Further, when CobiGen CLI is printing the available increments, it should also print the technical identifiers (`name` attribute) in brackets so it is easier to figure the option parameter for `-i` (if the feature is working after all).

**Comment by jdiazgon** [comment]
Hi @hohwille,

CobiGen uses the "Description" of the increments in order to search for them. Descriptions is what our users will see on the Eclipse UI. Name is just used internally for configuration of the increments, so it does not make much sense to be used.

![image](https://user-images.githubusercontent.com/31688036/81780339-aa678c80-94f6-11ea-8c46-b7c43870e42e.png)

**Comment by isandesh1986** [comment]
Yes, just verified. cli is searching based on the description.

<img width="947" alt="tos" src="https://user-images.githubusercontent.com/63033584/81938354-6a95c780-9612-11ea-9a52-be61f1ee68e2.png">

<img width="949" alt="rest" src="https://user-images.githubusercontent.com/63033584/81938375-71243f00-9612-11ea-8483-6df6706c533b.png">

**Comment by hohwille** [comment]
Indeed. However, the decision to use the description that may contain special characters (including Unicode, German Umlauts, etc.) does not make sense to me. Also the description is typically very long while the name shall be a unique and short identifier that saves a lot of typing.
Anyhow, confirmed that it is working as you describe.

**Comment by maybeec** [comment]
I agree to @hohwille. Let's implement increment selection based on the name only. I think there is no backwards compatibility needed at this early point in time.
@isandesh1986 could you correct this or @jdiazgon is there anything from your thoughts contradictory to this proposal?

**Comment by jdiazgon** [comment]
> Let's implement increment selection based on the name only

If possible, I would use both the description and the name. If we do not find anything by name, then search by description. 

For instance, [crud_java_server_app_complex](https://github.com/devonfw/cobigen/blob/master/cobigen-templates/templates-devon4j/src/main/templates/crud_java_server_app_complex/templates.xml#L38) has an increment with values `name="logic_impl_complex" description="CRUD UC logic"`. They are pretty different from each other and a normal user would search for `UC` or `CRUD UC` which may then miss it if we only use the name.

**Comment by maybeec** [comment]
@jdiazgon, got your point.
Is the CLI already able to do fuzzy matching of user inputs with increments? If so, this might be valuable. Anyhow, I would tend to say, name is always winning, i.e. in the unlikely case, where some name equals some other's increment description.

**Comment by jdiazgon** [comment]
> Is the CLI already able to do fuzzy matching of user inputs with increments?

Yeah. We are using Jaccard distance for the[ strings passed](https://github.com/devonfw/cobigen/blob/master/cobigen-cli/cli/src/main/java/com/devonfw/cobigen/cli/commands/GenerateCommand.java#L566) by the user.

**Comment by jdiazgon** [comment]
I have an idea that maybe could work for everyone:

When the user tries so search an increment by name, CobiGen will internally search all the increments that either have a matching name OR description. But the found increment will only be printed using the description.

For instance:

```
> cobigen generate -i complex

Found increments:
(0) All
(1) CRUD UC logic
(2) CRUD UC logic (CTO's)

```
And the same applies to

```
> cobigen generate -i UC

Found increments:
(0) All
(1) CRUD UC logic
(2) CRUD UC logic (CTO's)

```
Why? If you are an advanced user enough to know how the templates configuration work and you search by name, then for sure you know the description. However, if you are a user that does not know about internal CobiGen configuration, searching by description will make much more sense.

WDYT?

**Comment by maybeec** [comment]
yes agreed. Good summary of the discussion! But if it directly equals a name, you would directly start generation rather than providing a selection, I would say.

For example, if you have the following increments:

```xml
<increment name="complex" ... />
<increment name="complex_and_more" ... />
```

then `> cobigen generate -i complex` should directly start generation to make sure that any scripted custom automation based on the CLI might not break.

**Comment by jdiazgon** [comment]
That makes sense. Thanks!

**Comment by maybeec** [comment]
@isandesh1986 could you please check for the requirement mentioned in my last comment? I am pretty sure that this is not yet handled in the PR properly.

**Comment by isandesh1986** [comment]
> @isandesh1986 could you please check for the requirement mentioned in my last comment? I am pretty sure that this is not yet handled in the PR properly.

Modified accordingly and committed the code. Kindly review the same.
