### ISSUE TITLE
 Filename too long on checking out on windows 10

### ISSUE THREAD

**Issue by StefanHumberg** [devonfw/cobigen#1196]
### Expected behavior

I was hoping to be able to at least clone cobigen, but:

### Actual behavior

c:\>git clone https://github.com/devonfw/cobigen.git
Cloning into 'cobigen'...
remote: Enumerating objects: 125, done.
remote: Counting objects: 100% (125/125), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 55093 (delta 35), reused 77 (delta 13), pack-reused 54968R
Receiving objects: 100% (55093/55093), 22.98 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (23890/23890), done.
error: unable to create file cobigen-maven/cobigen-maven-systemtest/src/test/resources/testdata/systemtest/Devon4JTemplateTest/templates-devon4j/src/main/templates/crud_java_server_app/templates/java/${variables.rootPackage}/${variables.component}/logic/api/to/${variables.entityName}Eto.java.ftl: Filename too long
error: unable to create file cobigen-maven/cobigen-maven-systemtest/src/test/resources/testdata/systemtest/Devon4JTemplateTest/templates-devon4j/src/main/templates/crud_java_server_app/templates/java/${variables.rootPackage}/${variables.component}/logic/api/to/cobigen.properties: Filename too long
error: unable to create file cobigen-maven/cobigen-maven-systemtest/src/test/resources/testdata/systemtest/Oasp4JTemplateTest/templates-oasp4j/crud_java_server_app/templates/java/${variables.rootPackage}/${variables.component}/dataaccess/impl/dao/${variables.entityName}DaoImpl.java.ftl: Filename too long
Updating files: 100% (1632/1632), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. git clone https://github.com/devonfw/cobigen.git

### Affected version:

* OS: Windows 10

**Comment by maybeec** [comment]
Hi @StefanHumberg, in CobiGen we have to maintain long paths as of the template structure.
Therefore, please execute once `git config --system core.longpaths true` on your system, which will enable longpaths by git such that you will be able to clone cobigen repo successfully.
