### ISSUE TITLE
Eclipse Plugin: Bad performance on huge classpath

### ISSUE THREAD

**Issue by dachiaradia** [devonfw/cobigen#1220]
### Expected behavior

As a user, I want to generate fast so that I don't have to wait 2 minutes to generate.

### Actual behavior
The generation takes 2-5 minutes for huge projects and entities with 30+ properties.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Get a java project with a total of 30 MB libraries.
2. Get any type of source file for generation with a lot of properties e.g. an entity with 30+ properties.
3. Hit generate on the entities file.
4. Eclipse freezes for 2-5 minutes and then shows the generation wizard.
5. All further steps will complete with normal response time.

### Comments/Hints:
I checked the internals of the CobiGen and the problem seems to be the determination of all properties which belong to the source class. The eclipse dependencies are handed over to QDox via an URL classloader which contains all classpath entries of the eclipse project (in our case 30 MB). QDox does then internally a lot of lookup on this classloader to build the source model for CobiGen and this consumed most of the time.

Not sure if we are just unlucky with the classpath size + the amount of properties or if others experience this problem too. Also, it seems to be quite inefficient to build up a model by QDox from scratch while Eclipse already contains the whole type model for the source file (obviously caused by the difference interfaces to the CobiGen core).

### Affected version:

* OS: Windows

**Comment by maybeec** [comment]
Hi @dachiaradia, thanks for the feedback.
The long waiting time before the pop-up opens might be caused as all plug-ins are installed in your eclipse which might even not been used in your case. In this case you can easily speed up by removing unnecessary plug-ins from your eclipse instance.
Tsplugin for merging and reading typescript as well as openapi plugin for reading openapi specifications are such performance eaters, so uninstall them if not needed. 

Regarding qdox, this is needed to provide merge abilities as well as getting source code like comments which will not be available in an reflection model. Anyhow, qdox is very fast and is just reading the file selected and doing class lookups only in the classpath.
I barely doubt that this is the bottleneck here.

Could you try uninstalling and give feedback about the performance?

**Comment by dachiaradia** [comment]
Thanks a lot for the input. I tried with just the core and java plugin and it is much faster now. It seems I got lost during my analysis ...
