### ISSUE TITLE
property merger uses system specific line endings

### ISSUE THREAD

**Issue by LarsReinken** [devonfw/cobigen#1245]
### Expected behavior

As a Cobigen user, I want the merging of my files to use the line endings that are used in the input file so that I get no problems when using the file. 

### Actual behavior

the line endings of the operating system are used.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1.  merge files on Windows that use linux line endings.

### Related/Dependent Issues

#1242

**Comment by MikeSchumacherCapgemini** [comment]
Fixed as of #1249
