### ISSUE TITLE
OpenAPI gives "trigger does not match" error

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/cobigen#1273]
Open API code generation gives erorr

Steps to reproduce.
1.  Place the [devonfw_employee.yml](https://raw.githubusercontent.com/devonfw/cobigen/master/documentation/files/devonfw_employee.yml) in the base directory of the core module
2. Right click on the yml file and select Cobigen > Generate
3.  It gives the below error popup.

![image](https://user-images.githubusercontent.com/61968717/96823184-861abf00-1449-11eb-8335-d83a848ef5ef.png)

**Comment by jdiazgon** [comment]
It seems service `findEmployee` is duplicated on your yml file:

![image](https://user-images.githubusercontent.com/31688036/96837823-4c48b900-1447-11eb-9b2f-1ee768ee1d45.png)

You can check here https://editor.swagger.io/ the validation

**Comment by sujith-mn** [comment]
> It seems service `findEmployee` is duplicated on your yml file:
> 
> ![image](https://user-images.githubusercontent.com/31688036/96837823-4c48b900-1447-11eb-9b2f-1ee768ee1d45.png)
> 
> You can check here https://editor.swagger.io/ the validation

Removed and tried.. same error.

**Comment by MikeSchumacherCapgemini** [comment]
The problem right now is that for some reason having different matchers for `crud_openapi_angular_service_based_app` (componentDef) and `crud_openapi_angular_client_app` (EntityDef) leads to this error.

Putting the same for both makes generation possible but that would obviously not be correct, so we need to make sure that both the triggers are recognized properly.

**Comment by maybeec** [comment]
@jan-vcapgemini was this the issue you already addressed?

**Comment by jan-vcapgemini** [comment]
> 
> 
> @jan-vcapgemini was this the issue you already addressed?

Yes, and I've worked with @MikeSchumacherCapgemini on this issue too.

**Comment by MikeSchumacherCapgemini** [comment]
The only occurence of this problem has been disabled for now.
See #1278 for more information
