### ISSUE TITLE
Angular environment.ts gets merged faulty

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1291]
### Expected behavior

As a CobiGen user, I want to generate an angular client project from my Eto file.

Result of merged src/environments/environment.ts should look like:

```
export const environment = {
  production: false,
  restPathRoot: 'http://localhost:8081/',
  restServiceRoot: 'http://localhost:8081/services/rest/',
  security: 'jwt',
};
```

### Actual behavior

After generating the project by following the steps on:
https://github.com/devonfw/cobigen/wiki/howto_angular-client-generation
The merged src/environments/environment.ts file gets merged with an invalid format.

Result looks like this:
```
export const environment: = {
    production: false,
    restPathRoot: 'http://localhost:8081/',
    restServiceRoot: 'http://localhost:8081/services/rest/',
    security: 'jwt'
};
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Follow steps on: https://github.com/devonfw/cobigen/wiki/howto_angular-client-generation using the [my-thai-star](https://github.com/devonfw/my-thai-star) project
2. Generate from my-thai-star\java\mtsj\api\src\main\java\com\devonfw\application\mtsj\general\logic\api\to\BinaryObjectEto.java

### Related/Dependent Issues
https://github.com/devonfw/devon4ng-application-template/issues/189

### Affected version:

* CobiGen Eclipse Plug-in	7.1.0.202012101009
* CobiGen Eclipse Plug-in	7.0.0
* CobiGen - TypeScript Plug-in 7.1.0

**Comment by sujith-mn** [comment]
`environment.ts` and `environment.prod.ts` are not part of cobigen code generation
https://github.com/devonfw/cobigen/pull/1270

**Comment by maybeec** [comment]
@jan-vcapgemini could you please also create a related issue on the ts-merge to work on?

**Comment by maybeec** [comment]
@jan-vcapgemini do we also have to adapt templates here?

**Comment by maybeec** [comment]
Have a look at #1270 as stated above. The environment.ts file has been removed temporarily from the templates. Possibly you can restore it to reproduce the error.

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-Templates-61dbfc1d95d674001ae9fcc4/issues/devonfw/cobigen/1291?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @LarsReinken @mdukhan @MikeSchumacherCapgemini @jan-vcapgemini

**Comment by maybeec** [comment]
tracked in devonfw/ts-merger#67
