### ISSUE TITLE
Incomplete type definition of contant

### ISSUE THREAD

**Issue by scerroni** [devonfw/cobigen#1361]
When i try to generate a client Angular APP, the "environment.ts" files i Supposed are correct, without a ":" after the definition.

export const environment = {
    production: false,
    restPathRoot: 'http://localhost:8081/',
    restServiceRoot: 'http://localhost:8081/services/rest/',
    security: 'jwt'
};

### Actual behavior -->

export const environment: = {
    production: false,
    restPathRoot: 'http://localhost:8081/',
    restServiceRoot: 'http://localhost:8081/services/rest/',
    security: 'jwt'
};

Stes to reproduce:
Cobigen --> Generate --> Angular Client

**Comment by LarsReinken** [comment]
#1291
