### ISSUE TITLE
OpenApi Plug-in EntityNameRegex matcher is not working with other triggers.

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1375]
### Expected behavior

As a CobiGen OpenAPI Plug-in user, I want CobiGen to detect Entities by regular expressions so that I can filter the entities I want to generate from.

### Actual behavior

When using an OpenAPI trigger with a regex matcher f.e. ".*le." the Generate command returns no templates to generate if other triggers than the regex trigger are present in the context.xml.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create a simple [custom template](https://github.com/devonfw/cobigen/wiki/howto_create-external-plugin#templates-creation)
2. Update the CobiGen OpenAPI Plug-in to the latest version using: [stable Eclipse plug-in release](https://devonfw.com/cobigen/updatesite/stable/)
3. Add a trigger with an EntityNameRegex matcher to your context.xml:
`<matcher type="EntityNameRegex" value=".*le.">
      <variableAssignment type="property" key="entityName" value="name"/>
    </matcher>`
4. Try to generate from a [test yaml file](https://github.com/devonfw/cobigen/wiki/cobigen-openapiplugin#full-example).

### Affected version:
CobiGen - OpenAPI Plug-in 2021.8.1

**Comment by jan-vcapgemini** [comment]
When using more than 12 other triggers in the context.xml, then the generation ignores the EntityNameRegex with ".*le.". If one trigger is removed, it successfully detects the matcher.

An EntityNameRegex matcher with ".*" gets detected independent of the amount of triggers though.

**Comment by LarsReinken** [comment]
When the id of the "crud_openapi_ionic_client_app"-Trigger is changed to something else, the EntityNameRegex matcher seem to work as intended, independent of the amount of trigger in total.
