### ISSUE TITLE
Generate from devonfw example project with CLI is not working

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1389]
### Expected behavior

As a CobiGen CLI user, I want to generate artifacts from the devonfw example project using a simple CustomerEntity.

### Actual behavior
When running generate on the example project, following error occurs:

`Running: cobigen generate cobigenexample/core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api/CustomerEntity.java
[DEBUG] Input files and output root path confirmed to be valid.
[ERROR] Invalid input for CobiGen, please check your input file 'cobigenexample/core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api/CustomerEntity.java'
[ERROR] There are no common Templates/Increments which could be generated from every of your inputs. Please think about executing generation one by one input file.
java.util.InputMismatchException: No compatible input files.
        at com.devonfw.cobigen.cli.commands.GenerateCommand.preprocess(GenerateCommand.java:177)
        at com.devonfw.cobigen.cli.commands.GenerateCommand.doAction(GenerateCommand.java:115)
        at com.devonfw.cobigen.cli.commands.CommandCommons.call(CommandCommons.java:36)
        at com.devonfw.cobigen.cli.commands.CommandCommons.call(CommandCommons.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1100(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at com.devonfw.cobigen.cli.CobiGenCLI.main(CobiGenCLI.java:37)
[INFO ] Failed`

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

Same steps can be easily followed here: https://www.katacoda.com/devonfw-dev/scenarios/170_remove-adapttemplatescobigen_cobigen

1. Create a fresh devonfw ide project
2. Run: devon cobigen
3. Switch to your workspaces/main directory
4. Run: devon java create com.example.application.cobigenexample
5. Run: mkdir -p /root/devonfw/workspaces/main/cobigenexample/core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api
6. Create a simple CustomerEntity.java with some variables in the newly created folder
7. Switch directory to cobigenexample
8. Run: devon mvn clean install -Dmaven.test.skip=true
9. Run: devon cobigen generate core/src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api/CustomerEntity.java
10. Use: 1,3,5,6,8

### Comments/Hints:

- Running a generate from Eclipse with the same input works fine.
- It seems that the problem is related to "**_dependency:resolve -Djansi.force=true -Djansi.passthrough=true_**" arguments being passed to mvn https://github.com/devonfw/cobigen/blob/9420c2dd9bd7b76c27018a9498ff9fd52b988eec/cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/util/MavenUtil.java#L100 when executed from the cobigenexample/core directory.
- When executing the dependency:resolve + arguments inside the cobigenexample folder and starting the generate command then the dependencies get resolved, but https://github.com/devonfw/cobigen/blob/9420c2dd9bd7b76c27018a9498ff9fd52b988eec/cobigen-plugins/cobigen-javaplugin-parent/cobigen-javaplugin/src/main/java/com/devonfw/cobigen/javaplugin/inputreader/JavaParserUtil.java#L124 fails instead, as it reports that it can't find the pom.xml.
- When the content of the cobigenexample/core/.flattened-pom.xml was copied over the pom.xml of core, then the generate process works fine.

### Affected version:

* devonfw ide 2021.04.002
* CobiGen CLI 2021.08.001
* javaplugin 2021.08.001

**Comment by maybeec** [comment]
Have you tried generating like this in step 9 while beforehand switching to core project? It's not the intended solution but might help to understand the problem. 

devon cobigen generate src/main/java/com/example/application/cobigenexample/customermanagement/dataaccess/api/CustomerEntity.java

**Comment by jan-vcapgemini** [comment]
@maybeec Yes, I've tried it and got a NPE.
It looks like the input file path is interpreted in a relative manner. This results in the recursion going back to its root src folder only failing to find a pom.xml. Then a null is being transferred to the output project path and the NPE thrown.
I will try to analyze this a bit deeper, thank you for your hint.

**Comment by jan-vcapgemini** [comment]
When providing an output path (with linux format slashes) the generate works fine.

**Comment by jan-vcapgemini** [comment]
This issue seems to be related to: https://github.com/devonfw/cobigen/issues/1117
The classObject of Freemarker templates becomes null when the JavaInputReader is detecting a JavaClass in the createModel method.
https://github.com/devonfw/cobigen/blob/e0e8af27ce480ee2fde70c0a7a5f1ef332af379a/cobigen-plugins/cobigen-javaplugin-parent/cobigen-javaplugin/src/main/java/com/devonfw/cobigen/javaplugin/inputreader/JavaInputReader.java#L93

**Comment by jan-vcapgemini** [comment]
After more debugging I've found out that several important exception messages were thrown.

java.lang.IllegalArgumentException: Could not find pom.xml for basedir: D:\devon_ide\workspaces\runtime-EclipsePluginVanilla\cobigenexample\core

org.apache.maven.model.building.ModelBuildingException: 26 problems were encountered while building the effective model for cobigenexample:cobigenexample-core:1.0.0-SNAPSHOT
[ERROR] Failed to determine Java version for profile jdk8 @ io.dropwizard.metrics:metrics-parent:4.1.18
[ERROR] Failed to determine Java version for profile doclint-java8-disable @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile compile-java8-release-flag @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile include-jdk-misc @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java8-test @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java9-mr-build @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java9-test @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java10-mr-build @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java10-test @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java11-mr-build @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java11-test @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java12-mr-build @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java12-test @ org.jboss:jboss-parent:36
[ERROR] Failed to determine Java version for profile java13-mr-build @ org.jboss:jboss-parent:36
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-jdbc:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for javax.persistence:javax.persistence-api:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.hibernate:hibernate-entitymanager:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for com.querydsl:querydsl-jpa:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for com.querydsl:querydsl-apt:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.hibernate.validator:hibernate-validator:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-webmvc:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for com.h2database:h2:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.flywaydb:flyway-core:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-actuator:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.springframework:spring-aop:jar is missing. @ 
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter-web:jar is missing. @

**Comment by jan-vcapgemini** [comment]
The problem with the missing pom.xml seems to be related to the dependencyManagement of the parent pom and the missing version numbers in the child pom.

**Comment by maybeec** [comment]
m-m-m/code#40 - .mvn folder interpretation issue on m-m-m
