### ISSUE TITLE
'devon project setup cobigen' tries to checkout non existing 'develop' branch.

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1400]
### Expected behavior

When running 'devon project setup cobigen' I expect no errors being reported in my console.

### Actual behavior

The project setup is trying to checkout the 'develop' branch, which is not existing anymore.

```
error: pathspec 'develop' did not match any file(s) known to git
Failed to run command: git checkout develop

******** ATTENTION ********
ERROR: Failed to run command git
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 1
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Install fresh devonfw
2. run devon project setup cobigen

### Affected version:

* devonfw 2021.04.002

**Comment by maybeec** [comment]
Should be fixed by devonfw/ide-settings#20
