### ISSUE TITLE
Cobigen CLI commands are not working

### ISSUE THREAD

**Issue by dixyushi** [devonfw/cobigen#1404]
### Expected behavior

As a developer, I want to perform some operations related to CobiGen through command Line  so that I can use different command for further development 

### Actual behavior
It is giving error. Attached image for reference.
![image](https://user-images.githubusercontent.com/72491437/136726565-74ec4cfb-5598-40df-b1f0-4cca8136357b.png)

### Steps to reproduce (bug) 

1. Install devon
2. Follow https://devonfw.com/website/pages/docs/master-cobigen.asciidoc_cobigen-cli.html for further details on commands.

**Comment by jan-vcapgemini** [comment]
I've checked the scripts of devonfw. It looks like the verbose option is enabled by default now.

https://github.com/devonfw/ide/blob/f1a4a8775c6428adccac8118b28198c09a786247/scripts/src/main/resources/scripts/command/cobigen#L40

You can use `devon cobigen -q` to disable verbose output instead now.
You can also check `devon cobigen help` for available commands.
The documentation seems to be outdated.

**Comment by LarsReinken** [comment]
the primary bug couldn't be reproduced with the current version of devonfw, even though there is an open Ticket to fix it:
https://github.com/devonfw/ide/issues/598

**Comment by MikeSchumacherCapgemini** [comment]
This does not seem to happen anymore with the latest version of devon and cobigen.
If this does happen again, plese notify us.
