### ISSUE TITLE
Adapt Templates fails with "old" CobiGen templates home directory content

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1418]
### Expected behavior

As a CobiGen Eclipse user I want to use the **Adapt Templates** command to import the CobiGen_Templates into my workspace.

### Actual behavior
The imported CobiGen_Templates project within Eclipse is empty.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Run Update Templates in Eclipse
2. Create an empty CobiGen_Templates folder in your .cobigen/templates home directory
3. Run Adapt Templates

### Comments/Hints:
After deleting the CobiGen_Templates folder from the .cobigen/templates directory, the Adapt Templates command works fine.

### Possible fix:
Programmatically clear the .cobigen/templates home directory when updating/installing CobiGen through devonfw.

### Affected version:

* CobiGen Eclipse Plug-in	2021.8.2

**Comment by maybeec** [comment]
Do we have a clear understanding of the root cause? Just deleting adapted templates might be critical as these templates might be customized. If we know the issue causing the fail we could come up with an automated quick fix.

**Comment by jan-vcapgemini** [comment]
The same issue occurs when trying to use the CobiGen CLI generate command on a fresh devonfw ide installation.
When a non valid (empty) CobiGen_Templates folder is still present in the .cobigen/templates directory, following error occurs:

```
InvalidConfigurationException: C:\Users\username\.cobigen\templates\CobiGen_Templates\src\main\templates\context.xml:
Could not find context configuration file
```

**Comment by jan-vcapgemini** [comment]
This issues occurs when executing cobigen adapt-templates.
The command just creates an empty CobiGen_Templates folder in the .cobigen home directory.
