### ISSUE TITLE
Split template sets in separate deployables

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1452]
As a cobigen developer, I want to deploy every template set in a separate deployable so that I can release each template set separately. Please setup all template sets under the groupId `com.devonfw.cobigen.templates`.

* [x] #1501
* [x] #1505
* [x] #1504
* [x] adapt templates should extract all installed sets (short term solution for #1509 / #1455)

**Comment by jan-vcapgemini** [comment]
What do you think about a "CobiGenTemplateSet_" prefix?
Like: "CobiGenTemplateSet_crud-java-server-app" to make template set projects easily distinguishable from other projects.
Should be a shorter prefix though.
