### ISSUE TITLE
Add environment variable to be able to configure CobiGen_Templates project folder directory manually

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1465]
As a CobiGen user, I want to set my custom CobiGen_Templates project directory manually so that I can easily switch/replace my templates project.

*Acceptance Criteria*
* [ ] document `COBIGEN_HOME` environment variable
* [ ] document configuration keys like `variables=` for the `.cobigen` property file

**Comment by maybeec** [comment]
There is quite a lot, what do you focus on?

Template path as cli parameter https://github.com/devonfw/cobigen/blob/master/cobigen-cli/cli-systemtest/src/test/java/com/devonfw/cobigen/cli/systemtest/AbstractCliTest.java#L131

There is also a way of specifying the path directly by the environment variable `COBIGEN_HOME` pointing to a path, adding the `.cobigen` property file with the property `templates=` pointing to the template path. All details here:
https://github.com/devonfw/cobigen/blob/master/cobigen/cobigen-core-api/src/main/java/com/devonfw/cobigen/api/constants/ConfigurationConstants.java#L63

**Comment by jan-vcapgemini** [comment]
It looks like the whole documentation is existing already: https://github.com/devonfw/cobigen/wiki/cobigen-core_configuration#configuration
We just need to add the new 'template-sets' variable to our documentation.
