### ISSUE TITLE
Optimize class path cache files handling/generation

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1476]
Continuation of: #1430

As a CobiGen CLI user, I want CobiGen to handle my class path cache files more effective and less error prone.

- [x] Conceptualize new class path cache file handling/generation
- [x] Validate class path cache file integrity (check if dependencies exist)

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-Templates-61dbfc1d95d674001ae9fcc4/issues/devonfw/cobigen/1476?planning-poker) with ZenHub @mdukhan @jan-vcapgemini @EduardKrieger @ZakariaeMkassi @Ali7223
