### ISSUE TITLE
Add functionality to contextConfigurationUpgrader to upgrade to config v3.0+

### ISSUE THREAD

**Issue by MikeSchumacherCapgemini** [devonfw/cobigen#1502]
As a Cobigen user, I want to be able to let Cobigen upgrade my adapted template configuration so that i don't have to split my monolithic context.xml manually.

* [x] upgrade users context.xml, including splitting into template sets (one per trigger) and copy templates of each template folder to corresponding template-set
* [x] replicate all java utils to all template sets
* [x] replicate all pom dependencies to all template sets

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-Templates-61dbfc1d95d674001ae9fcc4/issues/devonfw/cobigen/1502?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini
