### ISSUE TITLE
Discovery of template sets

### ISSUE THREAD

**Issue by LarsReinken** [devonfw/cobigen#1517]
As a user, I want cobigen to discover template sets from maven repositories as specified by my `settings.xml`.

*Acceptance Criteria*
* [x] The discovery should return a set of `template-set.xml` representing internal configuration objects including all human readable data, but excluding all templates / triggers etc representations and analysis!
* [x] The discovery should discover `template-set.xml` from the repositories configured in settings.xml
* [x] discovery should take care of the user configuration as implemented in #1511

**Comment by jan-vcapgemini** [comment]
It looks like we still need to implement a separate XML reader for the template-set.xml files as well as a downloader to be able to provide the information which is required in the 1st action point.
