### ISSUE TITLE
template-set.xml is deployed separately

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1521]
As a cobigen user, I want to have a performant lookup of available template sets so that I feel comfortable in managing template sets easily. Therefore, information about template-sets should be retrieved without downloading or even extracting a huge amount of data or zip files.

*Acceptance Criteria* 
* [x] The template-set.xml file should be deployed as an additional deployable in the maven process
* [x] The template-set.xml should match the same naming convention like it is automatically done for the pom.xml on deploying to the local or remote m2 repository

Implementation Hint: http://www.mojohaus.org/build-helper-maven-plugin/attach-artifact-mojo.html should do the job easily to add another xml to the deployables.

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1521?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini

**Comment by Ali7223** [comment]
Templateset.xml was added into the root directory of the project and  'build-helper-maven plugin with id attach artifact'  was added in the pom.xml file which deploys all the files alongside jar and pom.xml which are mentioned in the <artifact>tag of this plugin under configuration tag with their respective file paths and types .
