### ISSUE TITLE
Eclipse generate throws IllegalAccessError when generating from source code 

### ISSUE THREAD

**Issue by mdukhan** [devonfw/cobigen#1526]
### Expected behavior

As a CobiGen Eclipse user, I want CobiGen to complete the generate process when generating from JPA entity inside the source code. Not from the project explorer.

### Actual behavior

Nothing gets generated. In the worst case, Eclipse throws an IllegalAccessError.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Go inside the source code of the file you want to generate from. 
2. Select for example the class name and right click.
3. Select cobigen->generate.

**Comment by jan-vcapgemini** [comment]
The getActiveWorkbenchWindow loops really long in: https://github.com/devonfw/cobigen/blob/d955e2898331723e77e7660c5454557077870541/cobigen-eclipse/cobigen-eclipse/src/com/devonfw/cobigen/eclipse/common/tools/PlatformUIUtil.java#L47-L52 which gets called from here: https://github.com/devonfw/cobigen/blob/d955e2898331723e77e7660c5454557077870541/cobigen-eclipse/cobigen-eclipse/src/com/devonfw/cobigen/eclipse/generator/GeneratorWrapperFactory.java#L103-L114

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1526?planning-poker) with ZenHub @GuentherJulian @jan-vcapgemini @mdukhan
