### ISSUE TITLE
Inform the user about deprecation and upgrade options

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1531]
As a cobigen user, I want to get automatically informed about the conceptual changes of the configuration going from monolithic template configuration folder to a modular template-set configuration folder. I want to get offered information (#1516).

*Acceptance Criteria*
* [x] If cobigen reads my monolithic template configuration, which is deprecated, I want to get offered an upgrade option and get informed about the process and steps to be performed
* [x] To properly make my decision in the moment of time, I would like to get more information about why I should do the upgrade and what is the impact 
* [x] the user should be asked every time a monolithic configuration is read from a folder 
* [x] make sure, that maven execution is not blocked by this feature at all

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/1531?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan

**Comment by mdukhan** [comment]
In Ticket #1519 we had to Ignore all Eclipse tests and some CLI tests, In this ticket these Tests should be enabled, these are: 

* All Eclipse Tests
* All tests in GenerateCommandTest in CLI
