### ISSUE TITLE
Support for DAO in devon4j projects discontinued?

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1549]
Once CobiGen was supporting DAO (`Dao` and `DaoImpl`) also for devon4j. Later Repos have been added on top.
If I am not mistaken DAOs are only left in oasp4j templates and have been removed from devon4j templates.
Was this by accident or on purpose?

[ApplicationDao](https://github.com/devonfw/cobigen/blob/47e55bd203942e789eacc80056ac9713497e8de5/cobigen-templates/templates-devon4j/src/main/templates/crud_java_server_app/templates/java/%24%7Bvariables.rootPackage%7D/general/dataaccess/api/dao/ApplicationDao.java.ftl) is present in the `devon4j` templates but the actual templates for `Dao` and `DaoImpl` are gone and only left in `oasp4j`.

Are projects using DAO and devon4j no more supported by Cobigen?

**Comment by maybeec** [comment]
I thought it was simply completely replaced by the Spring Data Repository approach.
Nonetheless, I feel we should anyhow restore the support now as an additional template set within the modular configuration.

Further tracked in #1555
