### ISSUE TITLE
Restore DAO template support

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#1555]
As a architect, I want to be able ton continue using DAO approach so that I can continue working with DAOs instead of Spring Repositories.

Therefore, we should restore the deleted DAO templates now as a separate package within our modular configuration.

Requesting Discussion: #1549

*Acceptance Criteria*:
* Restore DAO templates from Git History
* Add old DAO templates as a new template set in our new cobigen-templates collection
* Verify compatibility towards current [devon4j getting-started project skeleton](https://devonfw.com/website/pages/docs/devonfw-guide_devon4j.wiki_devon4j.asciidoc_tutorials.html#devonfw-guide_devon4j.wiki_tutorial-newapp.asciidoc)
* Add regression test for templates (might be included already)

`*Further Reading*
https://devonfw.com/website/pages/docs/devonfw-guide_devon4j.wiki_guide-jpa.asciidoc.html#devonfw-guide_devon4j.wiki_guide-repository.asciidoc

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-Templates-61dbfc1d95d674001ae9fcc4/issues/devonfw/cobigen/1555?planning-poker) with ZenHub @Ali7223 @EduardKrieger @jan-vcapgemini @mdukhan @ZakariaeMkassi @Zylesto @quantumfate @morsymegahed

**Comment by maybeec** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-Templates-61dbfc1d95d674001ae9fcc4/issues/devonfw/cobigen/1555?planning-poker) with ZenHub @NelsonNew

**Comment by Zylesto** [comment]
I have done a little bit of research on the topic. The commit with the following hash is the last one containing dao: 8ec69f8d7ba7eb154532481db2633dd0f197b271. Here you can see the removal history: https://github.com/devonfw/cobigen/commits/master?before=46bb19406003198ab2ad50db6a9ad2120c21b9e4+315&branch=master&path%5B%5D=cobigen-templates&qualified_name=refs%2Fheads%2Fmaster

**Comment by jan-vcapgemini** [comment]
It appears that this issue can be closed.

After recovering the old DAO template, it became obvious that the outdated way of handling **PaginatedListTo** using **io.oasp** does not suffice.

We can now either rewrite a completely new Paginator or remove the support for DAO and keep using **springframework repositories** instead.

I'd recommend to check if DAO is still being used in projects and if not, to close this issue.

**Comment by maybeec** [comment]
Closing it. If there is any interest please reopen
