### ISSUE TITLE
cobigen-cli: UnsupportedCharsetException: cp65001

### ISSUE THREAD

**Issue by hohwille** [devonfw/cobigen#1591]
### Expected behavior

As a cobigen-cli user, I want `cg` to work without hussle so that I can directly use it.

### Actual behavior

```
# cg
[DEBUG] Current working directory: D:\projects\devonfw
Exception in thread "main" java.nio.charset.UnsupportedCharsetException: cp65001
        at java.base/java.nio.charset.Charset.forName(Charset.java:529)
        at picocli.CommandLine.getStderrEncoding(CommandLine.java:14531)
```

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. install cobigen (`devon cg setup`, run `devon`)
2. run cobigen (`cg`)

### Related/Dependent Issues

https://github.com/remkop/picocli/issues/1474

### Comments/Hints:

Simply upgrade picocli version.

### Affected version:

* OS: Windows

**Comment by KHucklenbroich** [comment]
Not reproducible?
