### ISSUE TITLE
Create Wiki page for devonfw cobigen ide setup for intellij

### ISSUE THREAD

**Issue by jan-vcapgemini** [devonfw/cobigen#1608]
As a CobiGen developer, I want to use the intellij IDE so that I don't have to rely completely on the Eclipse IDE.

We need to create an easy intellij configuration guide based on the latest tech talk by @Lur1an

**Comment by professorabhay** [comment]
Hello, I am interested to work on this issue.
I am new in open source but for sure I can do this.
please assign it to me than I should start working on this.

**Comment by Lur1an** [comment]
@professorabhay This ticket is quite peculiar as it depends on a tech talk I gave in our intern CobiGen team. But feel free to look at other issues if you want to contribute!
