### ISSUE TITLE
Deployment Process for Template Sets

### ISSUE THREAD

**Issue by NelsonNew** [devonfw/cobigen#1638]
As a cobigen user, I want to be able to download the latest template sets so that I could use them instead of the templates.

*Acceptance Criteria:*
* [x] Tests which simulate the new download process
* [x] Deployment of Template Sets needs to be simulated and tested

**Comment by NelsonNew** [comment]
Malte, could you deploy the snapshots?

**Comment by jan-vcapgemini** [comment]
SNAPSHOTs were deployed by @maybeec
I had to adjust the ArtifactRetriever to handle SNAPSHOT versions too.
One test was added (downloads artifacts from sonatype, even if no maven settings were found)
Changes were merged into #1633.
