### ISSUE TITLE
Sencha combobox generation from enums doesn't work as expected

### ISSUE THREAD

**Issue by AlexanderRettkowski** [devonfw/cobigen#289]
When generating Sencha CRUD code, enums aren't interpreted as expected. Following the devon guide, I'd expect the generation of a store linked to the combobox and containing all the values from the enum. Instead, it seems a store from the restaurant sample application is copied. Furthermore, in the bind-section of the combobox, the value is generated completely in lower case, which produces an exception of the type com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException (Unrecognized field ...)

**Comment by maybeec** [comment]
Sencha is not supported anymore
