### ISSUE TITLE
Javamerge does not merge annotations

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#430]
Currently, the java merger does not merge annotations.
So far there are two restriction after implementation of this ticket:
1. Annotations are not merged recursively as it's not easy to identify "matching" annotations within an array
2. [Repeating annotations](https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html) defined next to each other could not be identified / differentiated for a proper merge, therefore, we need to overwrite / ignore all annotations of a given scope as a block

*Acceptance Criteria*
* [x] Annotations, which are not yet there should be added
* [x] All annotations should be replaced or not replaced
* [x] Annotations should be merged the same for fields, methods, classes

**Comment by jdiazgon** [comment]
The problem persists. The way to reproduce it:

1. Create a Java entity like this one:

```Java
import javax.persistence.Entity;
import javax.persistence.GeneratedValue; 
import javax.persistence.GenerationType; 
import javax.persistence.Column; 

public class EmployeeEntity {

  @Column(name = "EMPLOYEEID")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long employeeId;

  @Column(name = "NAME")
  private String name;

  @Column(name = "SURNAME")
  private String surname;

  @Column(name = "EMAIL")
  private String email;

}
```

2. Select it for generation, and use increment `Entity Infrastructure`.
3. It should generate the following annotations on top of the class, but it is not doing so:
```Java
@Entity
@javax.persistence.Table(name = "Employee")
```

**Comment by maybeec** [comment]
closed in favor of  #1053

**Comment by GuentherJulian** [comment]
The problem still exists

<details>
  <summary>Input EmployeeEntity.java</summary>
  
```
package com.example.domain.myapp.employeemanagement.dataaccess.api;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

public class EmployeeEntity {

  @Column(name = "EMPLOYEEID")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long employeeId;

  @Column(name = "NAME")
  private String name;

  @Column(name = "SURNAME")
  private String surname;

  @Column(name = "EMAIL")
  private String email;

  /**
   * @return employeeId
   */
  public Long getEmployeeId() {

    return this.employeeId;
  }

  /**
   * @param employeeId new value of {@link #getemployeeId}.
   */
  public void setEmployeeId(Long employeeId) {

    this.employeeId = employeeId;
  }

  /**
   * @return name
   */
  public String getName() {

    return this.name;
  }

  /**
   * @param name new value of {@link #getname}.
   */
  public void setName(String name) {

    this.name = name;
  }

  /**
   * @return surname
   */
  public String getSurname() {

    return this.surname;
  }

  /**
   * @param surname new value of {@link #getsurname}.
   */
  public void setSurname(String surname) {

    this.surname = surname;
  }

  /**
   * @return email
   */
  public String getEmail() {

    return this.email;
  }

  /**
   * @param email new value of {@link #getemail}.
   */
  public void setEmail(String email) {

    this.email = email;
  }

}
```
</details>

<details>
  <summary>Result after GobiGen EmployeeEntity.java</summary>
  
```
package com.example.domain.myapp.employeemanagement.dataaccess.api;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import com.example.domain.myapp.employeemanagement.common.api.Employee;
import com.example.domain.myapp.general.dataaccess.api.ApplicationPersistenceEntity;

public class EmployeeEntity extends ApplicationPersistenceEntity implements Employee {

  @Column(name = "EMPLOYEEID")
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long employeeId;

  @Column(name = "NAME")
  private String name;

  @Column(name = "SURNAME")
  private String surname;

  @Column(name = "EMAIL")
  private String email;

  private static final long serialVersionUID = 1L;

  /**
   * @return employeeId
   */
  public Long getEmployeeId() {

    return this.employeeId;
  }

  /**
   * @param employeeId new value of {@link #getemployeeId}.
   */
  public void setEmployeeId(Long employeeId) {

    this.employeeId = employeeId;
  }

  /**
   * @return name
   */
  public String getName() {

    return this.name;
  }

  /**
   * @param name new value of {@link #getname}.
   */
  public void setName(String name) {

    this.name = name;
  }

  /**
   * @return surname
   */
  public String getSurname() {

    return this.surname;
  }

  /**
   * @param surname new value of {@link #getsurname}.
   */
  public void setSurname(String surname) {

    this.surname = surname;
  }

  /**
   * @return email
   */
  public String getEmail() {

    return this.email;
  }

  /**
   * @param email new value of {@link #getemail}.
   */
  public void setEmail(String email) {

    this.email = email;
  }

}
```
</details>

```
@Entity
@javax.persistence.Table(name = "Entity")
```
is missing in the merged file

**Comment by LarsReinken** [comment]
current behaviour: 
- If the merge strategy is javamerge_override, property annotations of the patchfile are used.
- If the merge strategy is javamerge, property annotations of the basefile are used.
- The class annotations aren't changed at all, no matter whether javamerge_override or javamerge is used.
the expected behaviour 
- Obviously it doesn't make sense, to ignore the class annotation of the patchfile if javamerge_override is used as strategy.

Besides the previous point it becomes more complicated to define the expected behaviour. You might expect the merged file to contain all annotations, if the basefile has one annotation and the patchfile has another. For example:
  - basefile annotation: @Entity
  - patchfile annotation: @javax.persistence.Table(name = "vehicle")

that would cause problems for some annotations though. For example: 
  - basefile annotation: @Entity(tableName = "vehicles")
  - patchfile annotation: @Entity(tableName = "vehicle", primaryKey = "id")

To solve these merging problems cobigen needs to know the semantics of the annotation and would therefore require the templates to offer mergestrategies for specific annotations.

**Comment by maybeec** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/CobiGen-StoryMap-6257b8b9ecf3920015f4e871/issues/devonfw/cobigen/430?planning-poker) with ZenHub @EduardKrieger @GuentherJulian @jan-vcapgemini @LarsReinken @mdukhan @MikeSchumacherCapgemini
