### ISSUE TITLE
Move from Jenkins to GitHub actions or travis

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#541]
This step has to be done if we already are open source as otherwise, we cannot enable travisci for the closed repository. As our jenkins build is already quite complex please consider the following links, which might help:

https://docs.travis-ci.com/user/conditional-builds-stages-jobs#Specifying-conditions
http://www.lorenzobettini.it/2015/07/running-swtbot-tests-in-travis/

also consider #510 and #533.

**Comment by maybeec** [comment]
Currently, we have an issue with travis build as the CI updatesites are deployed to an internal server. We have to first get a public deployment server to be able to run everything in the cloud.

**Comment by maybeec** [comment]
Might be interesting in future for deployment: https://gist.github.com/letmaik/4060735

**Comment by jdiazgon** [comment]
From @MikeSchumacherCapgemini comments:
> I have seen an example of a wiki build script in travis CI.

>  I haven't really looked into GitLab yet, but starting march next year, it will only be available with silver GitLab membership, which costs 19$ per month per user, so the question is if it's worth the money if Travis does what we want

**Comment by maybeec** [comment]
No, unfortunately there is no money :) I would have loved to play around with GitLab CI.
It looks awesome!

**Comment by maybeec** [comment]
Builds are not automated on travis: https://travis-ci.com/github/devonfw/cobigen/branches
