### ISSUE TITLE
Create a meaningful Readme

### ISSUE THREAD

**Issue by maybeec** [devonfw/cobigen#542]
We should have a short but meaningful Readme, which should address the following points (potentially by linking into the WIKI).

* [x] What is CobiGen?
* [ ] Build status
* [x] Latest release (maven central)
* [x] How to install it?
* [x] How to contribute?

**Comment by jdiazgon** [comment]
With "build status" do you mean things like [this](https://github.com/dwyl/repo-badges)?

**Comment by maybeec** [comment]
yes

**Comment by maybeec** [comment]
Build status posponed until we have public CI/CD
