### ISSUE TITLE
util classloader for maven

### ISSUE THREAD

**Issue by Hellmy** [devonfw/cobigen#714]
### Expected behavior

As a template developer, I want to use the cobigen classloader in a maven project so that I can use reflection on other classes as described in https://github.com/devonfw/tools-cobigen/wiki/cobigen-core_configuration#java-template-logic

### Actual behavior

Not clear how to use the classloader or which classloader is referenced. Only classloader utils found lies in the eclipse package.

**Comment by jdiazgon** [comment]
Hi Hellmy, thank you very much for creating issues, they really help us to improve. 

I have been doing some investigations on this and I have found out some examples on how is the `ClassLoaderUtils` used:

- Inside /cobigen-eclipse/src/com/devonfw/cobigen/eclipse/generator/java/JavaInputConverter.java I can see:
```java 
ClassLoader projectClassLoader = ClassLoaderUtil.getProjectClassLoader(rootType.getJavaProject());
```

- Inside /cobigen-eclipse/src/com/devonfw/cobigen/eclipse/generator/CobiGenWrapper.java I found the following:
```java 
inputClassLoader = ClassLoaderUtil.getProjectClassLoader(configJavaProject, inputClassLoader);
```

Though in the case of templates development, I haven't found too much interesting information. I am sure @maybeec will put some light into this.

**Comment by Hellmy** [comment]
But the ClassLoaderUtil is in the eclipse package. Is this package usable from maven?

**Comment by maybeec** [comment]
@Hellmy you can directly access any class of the project built or any class of the util classes defined in the template project. The input class provided for generation is the anchor to start with.
So in a template, you can use `classObject.getClassLoader().loadClass("what.ever.Class")`.
See https://github.com/devonfw/tools-cobigen/wiki/cobigen-javaplugin#java-input-reader for the model documentation.

**Comment by Hellmy** [comment]
Sounds good, I will try this out.
I want to generate a Elasticsearch index mapping definition, where the fields of my object must be heated in their resulting json. 
Is there any possibility to use another template for the loaded class, e. g. to start another generation within the current generation?

**Comment by maybeec** [comment]
So you mean, you want to generate a file (template) per field in your java class?

Unfortunately, that is currently not supported. Therefore, we have to adapt the java input reader. Would that be valueable for you?

**Comment by Hellmy** [comment]
Remark about `${classObject.getClassLoader().loadClass("some.package.ClassObject")}`
This results in 
```
The following has evaluated to null or missing:
==> classObject.getClassLoader  [in template "templates/foo.ftl" at line 21, column 3]
```

**Comment by maybeec** [comment]
The only option I see here is to use reflection in a Java util implementation.
So what you can do is to implement your own Java class in the CobiGen cofiguration folder and pass classObject as an parameter and returning string.

You can call the method by taking the simple name of the java util class implemented followed by regular java method call syntax like this:

.Util implementation
```java
class MyUtil {
 String toElasticSearchIndex(Class<?> classObject) {...}
}
```

.Template
```
${MyUtil.toElasticSearchIndex(classObject)}
```

**Comment by Hellmy** [comment]
I assumed this... So I have to build a string myself without a template. 
Are there any helpers from cobigen to work with reflectoin or do I have to do it all myself?

**Comment by maybeec** [comment]
Unfortunately, there is no abstracted reflection support in CobiGen. But you can use any library you want to use for implementation just by adding it to the templates's project pom.
So if you even find a library which already serializes an object to such kind of a string, I would be just one line.

**Comment by Hellmy** [comment]
That's kind of a task - have to look into this. Thank you for the hints.

**Comment by Hellmy** [comment]
I had my first tryouts and it feels like I will not need cobigen any more as everything will be done with java classes. So what would be still the benefit to use CobiGen in such a case?

**Comment by Hellmy** [comment]
So fine for me - we could close this ticket...
Should any documentation be extended. I can't figure out the best place for it perhaps a hint near the the https://github.com/devonfw/tools-cobigen/wiki/cobigen-javaplugin#java-input-reader ?
