### ISSUE TITLE
Variable assignment for external increments throws exception

### ISSUE THREAD

**Issue by jdiazgon** [devonfw/cobigen#747]
### Expected behavior

VariableAssignment should work in every case when defining external increments. 

### Actual behavior

If the external trigger does not define the variables needed, then an exception is thrown:

![image](https://user-images.githubusercontent.com/31688036/44912192-af3bdb00-ad29-11e8-9bf6-1fbef0e51b0d.png)

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. Create two triggers, one matches the input file and defines the variables, the other trigger does not.

```xml
<trigger id="valid_external_incrementref" type="xml" templateFolder="valid_external_incrementref">
  <containerMatcher type="xpath" value="./uml:Model//packagedElement[@xmi:type='uml:Class']"/>
  <matcher type="xpath" value="self::node()[@xmi:type='uml:Class']/ancestor::uml:Model">
    <variableAssignment type="xpath" key="className" value="self::node()/@name"/>
  </matcher>
</trigger>
    
<trigger id="valid_increment" type="xml" templateFolder="valid_increment">
    <matcher type="nodename" value="IShouldNotMatch">
    </matcher>
</trigger>
```

2. `valid_external_incrementref` defines the external incrementRef, while `valid_increment` defines the templates and increments.

**valid_external_incrementref**
```xml
  <increments>
    <increment name="externalIncrement" description="externalIncrement">
      <incrementRef ref="valid_increment::0"/>    
    </increment>
  </increments>
```
**valid_increment**
```xml
  <templateScans>
    <templateScan templatePath="templates" destinationPath="src/main"/>
  </templateScans>

  <increments>
    <increment name="0" description="0">
      <templateRef ref="templateDecl.java"/>
    </increment>
  </increments>
```

3. Try to generate and you will get the exception shown above.

If you define the same variableAssignment for both triggers, then it works fine. We should fix this so that the variableAssignment is resolved on both triggers.

### Related/Dependent Issues
#678

**Comment by jdiazgon** [comment]
After discussing with @lilliCao about this issue, we have found out that my steps to reproduce the error was not 100% accurate:

> Create two triggers, one matches the input file and defines the variables, the other trigger does not.

Actually, when one of the triggers does not match the input file, generation does not work. This should be addressed in another issue. For now, we can fix variable assignment only when both triggers match the input file.

**Comment by lilliCao** [comment]
After discussing again with @jdiazgon, we came to the conclusion that the following logic will be implemented to solve this issue:
e.g. trigger 1 defines template tp1 and increment inc1, trigger 2 defines a reference to inc1
1. If only trigger 2 matches, tp1 should be able to resolve all the variableAssignment defined by trigger 2
2. If both trigger match, tp1 should be able to resolve all the variableAssignment defined by trigger 1 and trigger 2. In case there are same variableAssignment from both triggers, the one from trigger 2 is resolved.

**Comment by jdiazgon** [comment]
Completely agree, thanks @lilliCao
