### ISSUE TITLE
Cobigen processbar 

### ISSUE THREAD

**Issue by mandybuchhold** [devonfw/cobigen#867]
### Expected behavior
When i use cobigen to generate code i want to see how long it takes until it is finished and i want the option to cancel the code generation (maybe if it takes too long). 

### Actual behavior
At the moment we have a processbar but it is not working as expected. Wenn i generate some code there is nothing happen and you can't use the cancel button its disabled. Not before the generation is nearly allready finished there appear a few more windows and then the generation is finished. Especially if i generate a lage amount of code, i have to wait a long time and don't know if it is still working or if eclipse suspended completly.

![grafik](https://user-images.githubusercontent.com/49148051/57135287-2807a100-6da9-11e9-869d-9774b6c5323b.png)

**Comment by jdiazgon** [comment]
Completely agree, we should enhance this.
