### ISSUE TITLE
Cobigen perfomance issues 

### ISSUE THREAD

**Issue by mandybuchhold** [devonfw/cobigen#868]
### Expected behavior
Faster working cobigen.

### Actual behavior
If i use cobigen in batch mode and have choose more than 10 files, cobigen is really slowly and it appears if eclipse suspended completly.

### Steps to reproduce (bug)
I tested this with 14 Enities an and generated the following increments.
It last about 15 minutes until it finished .
 
![grafik](https://user-images.githubusercontent.com/49148051/57136110-00fe9e80-6dac-11e9-8614-f1e78226c4c2.png)

I head from colleages who use the testdata builder, that they have the same performance issues, i think it is a general problem of cobigen.

**Comment by jdiazgon** [comment]
With the CobiGen CLI performance is improved greatly. Maybe we could try to parallelize CobiGen, but it seems more an Eclipse UI issue.
